[package]
name = "meksmith"
version = "0.0.1"
edition = "2024"
repository = "https://github.com/whiskeyo/meksmith.rs"

[[bin]]
name = "meksmith"
path = "src/bin/meksmith.rs"

[dependencies]
chumsky = { workspace = true, default-features = true }
thiserror = "2.0.18"
ariadne = "0.5.0"

[dev-dependencies]
tempfile = { workspace = true, default-features = true }
rstest = { workspace = true, default-features = true }
insta = "1.43.1"
