[package]
name = "meksmith-website"
version = "0.0.1"
edition = "2024"

[dependencies]
meksmith = { path = "../meksmith" }

leptos = { version = "0.8.2", features = ["csr"] }
leptos_router = "0.8.2"
console_error_panic_hook = "0.1.7"
web-sys = "0.3.77"
regex-lite = "0.1.6"
